### ISSUE TITLE
Adding opensearch tags to make the browser aware of it as a search engine

### ISSUE THREAD

**Issue by Ramblurr** [phronmophobic/cloogle#8]
You could add the necessary opensearch tags ([detailed on MDN](https://developer.mozilla.org/en-US/docs/Web/OpenSearch)), and then the browser would become aware of Cloogle as a search engine, and users like myself will be able to add it to their browser as a search engine type.

This feature is very handy. I already have a shortcut in my firefox to search github directly.

If you added this then users could create a shortcut to search Cloogle directly!

You can view source at https://github.com/search and ctrl+f for `opensearch` to see how easy it is.

**Comment by phronmophobic** [comment]
Ok, I just gave it a shot. Seems to work. Let me know if it works for you!

Thanks for the tip!

**Comment by Ramblurr** [comment]
Amazing!

Now this icon shows up in firefox:
![image](https://github.com/user-attachments/assets/f5b7cf2e-87d3-4988-bd65-a137175f3b15)

Clicking it adds Cloogle as a search engine.. then I setup a shortcut `@cl`:

![image](https://github.com/user-attachments/assets/f1e63481-cb20-4b6f-ba97-197456e33146)

So now when I type `@cl foobar` in the location bar, it searches cloogle!

Many thanks :)

**Comment by phronmophobic** [comment]
That's a pretty neat Firefox feature. I never knew it existed and now I'm probably going to use it all the time. Thanks!
